query GetReceipts {
  posReceiptsPage {
    posReceipts {
      id
      dateTime
      totalAmount {
        amount
      }
    }
    pagination {
      key
      totalElements
      offset
      limit
    }
  }
}
